what = (
    ('(A) Head Protection not worn' , '(A) Head Protection not worn' ),
    ('(B) Eye protection not worn' , '(B) Eye protection not worn'),
    ('(C) Face protection not worn' , '(C) Face protection not worn'),
    ('(D) Ear protection not worn', '(D) Ear protection not worn'),
    ('(E) Protective clothing not worn' , '(E) Protective clothing not worn'),
    ('(F) Leg/Feet protection not worn', '(F) Leg/Feet protection not worn'),
    ('(G) Hand protection not worn', '(G) Hand protection not worn'),
    ('(H) PPE in bad condition', '(H) PPE in bad condition'),
    ('(I) Wrong PPE for the job','(I) Wrong PPE for the job'),
    ('(J) Substandard PPE' , '(J) Substandard PPE'),
    ('(K) PPE not worn properly', '(K) PPE not worn properly'),
    ('(L) Respiration protection not worn', '(L) Respiration protection not worn'),
    ('(M) Body Protection not worn' ,'(M) Body Protection not worn'),
    ('(N) Wrong tool for the job',  '(N) Wrong tool for the job'),
    ('(O) Tools in bad condition', '(O) Tools in bad condition' ),
    ('(P) Tools not inpected', '(P) Tools not inpected'),
    ('(Q) Misuse', '(Q) Misuse'),
    ('(R) Uncertified tools' , '(R) Uncertified tools'),
    ('(S) Too heaving for manual lifting', '(S) Too heaving for manual lifting'),
    ('(T) Wrong mechanical manual lifting' , '(T) Wrong mechanical manual lifting'),
    ('(U) Lifting tool not inspected' , '(U) Lifting tool not inspected'),
    ('(V) Chemical not properly handled', '(V) Chemical not properly handled'),
    ('(W) Waste not properly disposed', '(W) Waste not properly disposed'),
    ('(X) In danger of struck' , '(X) In danger of struck'),
    ('(Y) In danger of striking against', '(Y) In danger of striking against'),
    ('(Z) In danger of caught by' ,'(Z) In danger of caught by'),
    ('(AA) In danger of fall/slip/trip' ,'(AA) In danger of fall/slip/trip'),
    ('(BB) In danger of electrocution' , '(BB) In danger of electrocution'),
    ('(CC) In danger of burnt' , '(CC) In danger of burnt'),
    ('(DD) Access obstructed' , '(DD) Access obstructed'),
    ('(EE) Tools/materials disorganized' , '(EE) Tools/materials disorganized'),
    ('(FF) Poor/Improper roping of', '(FF) Poor/Improper roping of'),
    ('(GG) Accumulation of rubbish', '(GG) Accumulation of rubbish'),
    ('(HH) Water is being polluted','(HH) Water is being polluted'),
    ('(II) Air being polluted', '(II) Air being polluted'),
    ('(JJ) Too much noise', '(JJ) Too much noise'),
    ('(KK) Soil being polluted','(KK) Soil being polluted'),
    ('(LL) Poor illumination', '(LL) Poor illumination'),
    ('(MM) Work without permission', '(MM) Work without permission'),
    ('(NN) Wrong permit', '(NN) Wrong permit'),
    ('(OO) Procedures / Standard not followed' , '(OO) Procedures / Standard not followed'),
    ('(PP) Wrong instruction on permit' , '(PP) Wrong instruction on permit'),
    ('(QQ) Permit procedure not follow' , '(QQ) Permit procedure not follow'),
    ('(RR) Inadequate HIP' , '(RR) Inadequate HIP'),
    ('(SS) Toolbox talk not given' , '(SS) Toolbox talk not given'),
    ('(TT) Driving recklessly' , '(TT) Driving recklessly'),
    ('(UU) Not wearing seat belt' ,'(UU) Not wearing seat belt'),
    ('(VV) Road traffic violation - eg. Speeding, no entry & ect' , '(VV) Road traffic violation - eg. Speeding, no entry & ect'),
    ('(WW) Vehicles / Transportation abuse' , '(WW) Vehicles / Transportation abuse'),
    ('(XX) Not inspected for compliance', '(XX) Not inspected for compliance'),
    ('(YY) Vehicle defects' ,'(YY) Vehicle defects'),
    ('(ZZ) Compliance' , '(ZZ) Compliance'),
    ('(AAA) Behavior & Attitude' , '(AAA) Behavior & Attitude'),

)

why = (
    ('(1) Not Informed', '(1) Not Informed'),
    ('(2) Languague Problem', '(2) Languague Problem'),
    ('(3) Not reasing permit', '(3) Not reading permit'),
    ('(4) Wrong interpretation of risk' , '(4) Wrong interpretation of risk'),
    ('(5) Wrong instruction' , '(5) Wrong instruction'),
    ('(6) No procedure' , '(6) No procedure'),
    ('(7) Lack of HSE Coaching / training' , '(7) Lack of HSE Coaching / training'),
    ('(8) Behavior & Attitude (intentionally)' , '(8) Behavior & Attitude (intentionally)'),
    ('(9) Negligence' , '(9) Negligence'),
    ('(10) Working condition', '(10) Working condition'),
    ('(11) Working layout' , '(11) Working layout'),
    ('(12) The design of equipment / tools' , '(12) The design of equipment / tools'),
    ('(13) Work habits' ,'(13) Work habits'),
    ('(14) Lack of skill' , '(14) Lack of skill'),
    ('(15) Time pressure' , '(15) Time pressure'),
    ('(16) Not requested' , '(16) Not requested'),
    ('(17) Physical limitations' , '(17) Physical limitations'),
    ('(18) Not supplied/available' , '(18) Not supplied/available'),
    ('(19) Lack of ownership' , '(19) Lack of ownership'),
    ('(20) Behavior & Attitude (not intentionally)' , '(20) Behavior & Attitude (not intentionally)'),
)

lsr = (
    ('(1) Work with a valid work permit when required' , '(1) Work with a valid work permit when required'),
    ('(2) Conduct gas test when required' , '(2) Conduct gas test when required'),
    ('(3) Verify isolation before work begins and use the specific life protecting equipment' , '(3) Verify isolation before work begins and use the specific life protecting equipment'),
    ('(4) Obtain authorization before entering a confined space' , '(4) Obtain authorization before entering a confined space'),
    ('(5) Obatin authorization before overriding or disabiling safety critical equipment' ,'(5) Obatin authorization before overriding or disabiling safety critical equipment'),
    ('(6) Protect yourself against a fall when working at height' , '(6) Protect yourself against a fall when working at height'),
    ('(7) Do not walk under a suspended load', '(7) Do not walk under a suspended load'),
    ('(8) Do not smoke outside designated smoking area' , '(8) Do not smoke outside designated smoking area'),
    ('(9) No alcohol or drugs while working or driving' , '(9) No alcohol or drugs while working or driving'),
    ('(10) While driving , do not use your phone and do not exceed limit' , '(10) While driving , do not use your phone and do not exceed limit'),
    ('(11) Wear your seat belts' , '(11) Wear your seat belts'),
    ('(12) Follow prescribed Journey Management Plan' ,'(12) Follow prescribed Journey Management Plan'),
)