# Generated by Django 4.1.7 on 2023-04-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_raised',
            field=models.DateField(blank=True, null=True),
        ),
    ]
