# Generated by Django 4.1.7 on 2023-04-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolboxtalk',
            name='presenter',
        ),
    ]
