# Generated by Django 4.1.7 on 2023-04-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0002_alter_incident_date_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='responsible_party',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
