# Generated by Django 4.1.7 on 2023-04-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0002_staff_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_happened', models.CharField(blank=True, max_length=100, null=True)),
                ('why_happened', models.CharField(blank=True, max_length=100, null=True)),
                ('date_raised', models.DateField(auto_now_add=True)),
                ('life_saving_rule', models.CharField(blank=True, max_length=100, null=True)),
                ('findings', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('discussion', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up', models.BooleanField(default=False)),
                ('follow_up_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('raised_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hseapp.staff')),
            ],
        ),
    ]
