# Generated by Django 4.1.7 on 2023-04-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0002_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='staff_position',
            new_name='position',
        ),
    ]
