# Generated by Django 4.1.7 on 2023-04-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0002_appuser_is_active_appuser_is_admin_appuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
