# Generated by Django 4.1.7 on 2023-04-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0003_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hseapp.staff'),
        ),
    ]
