# Generated by Django 4.1.7 on 2023-04-29 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0003_rename_staff_position_training_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='position',
            new_name='staff_position',
        ),
    ]
