# Generated by Django 4.1.7 on 2023-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0004_alter_incident_raised_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='life_saving_rule',
            field=models.CharField(blank=True, choices=[('(1) Work with a valid work permit when required', '(1) Work with a valid work permit when required'), ('(2) Conduct gas test when required', '(2) Conduct gas test when required'), ('(3) Verify isolation before work begins and use the specific life protecting equipment', '(3) Verify isolation before work begins and use the specific life protecting equipment')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='what_happened',
            field=models.CharField(blank=True, choices=[('(A) Head Protection not worn', '(A) Head Protection not worn'), ('(B) Eye protection not worn', '(B) Eye protection not worn'), ('(C) Face protection not worn', '(C) Face protection not worn'), ('(D) Ear protection not worn', '(D) Ear protection not worn')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='why_happened',
            field=models.CharField(blank=True, choices=[('(1) Not Informed', '(1) Not Informed'), ('(2) Languague Problem', '(2) Languague Problem'), ('(3) Not reasing permit', '(3) Not reading permit')], max_length=100, null=True),
        ),
    ]
