# Generated by Django 4.1.7 on 2023-04-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0004_toolboxtalk_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxtalk',
            name='presenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_talks_presenter', to='hseapp.staff'),
        ),
        migrations.AlterField(
            model_name='toolboxtalk',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_talks_supervissor', to='hseapp.staff'),
        ),
    ]
