# Generated by Django 4.1.7 on 2023-04-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0005_alter_toolboxtalk_presenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='yearly_leave_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='yearly_leave_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
