# Generated by Django 4.1.7 on 2023-04-02 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0005_alter_incident_life_saving_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
