# Generated by Django 4.1.7 on 2023-04-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0005_alter_training_staff_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='staff_position',
        ),
    ]
