# Generated by Django 4.1.7 on 2023-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0006_alter_incident_id_alter_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='short_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
