# Generated by Django 4.1.7 on 2023-04-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0006_staff_yearly_leave_days_staff_yearly_leave_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='yearly_leave_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
