# Generated by Django 4.1.7 on 2023-04-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0007_staff_yearly_leave_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='datelist',
            name='attendence_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datelist',
            name='staff_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hseapp.staff'),
            preserve_default=False,
        ),
    ]
