# Generated by Django 4.1.7 on 2023-04-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0007_staff_yearly_leave_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='what_happened',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
