# Generated by Django 4.1.7 on 2023-05-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0008_sitehazards_sitevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitehazards',
            name='sitevisit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hseapp.sitevisit'),
        ),
    ]
