# Generated by Django 4.1.7 on 2023-04-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0008_alter_incident_what_happened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='life_saving_rule',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='why_happened',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
