# Generated by Django 4.1.7 on 2023-05-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0009_alter_sitehazards_sitevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitehazards',
            name='sitevisit',
        ),
    ]
