# Generated by Django 4.1.7 on 2023-05-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0011_sitehazards_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitehazards',
            name='visit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
