# Generated by Django 4.1.7 on 2023-05-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0013_remove_sitehazards_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitehazards',
            old_name='sitevisit',
            new_name='visit',
        ),
    ]
