# Generated by Django 4.1.7 on 2023-05-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0014_rename_sitevisit_sitehazards_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitehazards',
            name='hazard',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sitehazards',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
