# Generated by Django 4.1.7 on 2023-05-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0015_alter_sitehazards_hazard_alter_sitehazards_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hseapp.staff')),
            ],
        ),
    ]
