# Generated by Django 4.1.7 on 2023-05-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0016_staffadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffadd',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hseapp.sitevisit'),
        ),
    ]
