# Generated by Django 4.1.7 on 2023-05-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0017_staffadd_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='inspection_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
