# Generated by Django 4.1.7 on 2023-05-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0018_sitevisit_inspection_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_incident', models.DateField(blank=True, null=True)),
                ('location_of_incident', models.CharField(blank=True, max_length=100, null=True)),
                ('task_performed', models.CharField(blank=True, max_length=1000, null=True)),
                ('what_happened', models.CharField(blank=True, max_length=1000, null=True)),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentinvestigation_investigator', to='hseapp.staff')),
                ('team_member_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentinvestigation_team_member_four', to='hseapp.staff')),
                ('team_member_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentinvestigation_team_member_one', to='hseapp.staff')),
                ('team_member_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentinvestigation_team_member_three', to='hseapp.staff')),
                ('team_member_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentinvestigation_team_member_two', to='hseapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(blank=True, max_length=200, null=True)),
                ('type_of_factor', models.CharField(blank=True, max_length=200, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=200, null=True)),
                ('when_will_fix', models.DateField(blank=True, null=True)),
                ('planned_completion_date', models.DateField(blank=True, null=True)),
                ('who_will_fix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hseapp.staff')),
            ],
        ),
    ]
