# Generated by Django 4.1.7 on 2023-05-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0020_incidentfactors_incidentinvestigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentinvestigation',
            name='summary_of_remedial_action',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
