# Generated by Django 4.1.7 on 2023-05-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0021_incidentinvestigation_summary_of_remedial_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentinvestigation',
            name='summary_of_incident_investigation',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
