# Generated by Django 4.1.7 on 2023-05-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0022_incidentinvestigation_summary_of_incident_investigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAndItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('dollar_value', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('identification_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_box', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hseapp.equipmentanditems')),
            ],
        ),
    ]
