# Generated by Django 4.1.7 on 2023-05-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0023_equipmentanditems_itemperbox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPerBox',
            new_name='ItemsPerBox',
        ),
    ]
