# Generated by Django 4.1.7 on 2023-05-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0027_rename_item_equipmentanditems_equipment_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentanditems',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipmentanditems',
            name='type_of_equipment_item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
