# Generated by Django 4.1.7 on 2023-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0028_equipmentanditems_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentanditems',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
