# Generated by Django 4.1.7 on 2023-06-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0029_equipmentanditems_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSEManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manangement_document', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
