# Generated by Django 4.1.7 on 2023-06-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0030_hsemanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HSEManagement',
        ),
    ]
