# Generated by Django 4.1.7 on 2023-06-03 07:32

from django.db import migrations, models
import hseapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0031_delete_hsemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSEManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=hseapp.models.upload_to)),
            ],
        ),
    ]
