# Generated by Django 4.1.7 on 2023-06-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0033_rename_description_hsemanagement_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsemanagement',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsemanagement',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
