# Generated by Django 4.1.7 on 2023-06-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0034_alter_hsemanagement_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsemanagement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='post_documents'),
        ),
    ]
