# Generated by Django 4.1.7 on 2023-06-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0035_hsemanagement_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsemanagement',
            name='document',
        ),
    ]
