# Generated by Django 4.1.7 on 2023-06-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0038_remove_hsemanagement_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('risk_description', models.CharField(blank=True, max_length=300, null=True)),
                ('likelihood_of_risk', models.CharField(blank=True, max_length=300, null=True)),
                ('impact_of_risk', models.CharField(blank=True, max_length=300, null=True)),
                ('severity', models.CharField(blank=True, max_length=300, null=True)),
                ('owner', models.CharField(blank=True, max_length=300, null=True)),
                ('mitigating_action', models.CharField(blank=True, max_length=300, null=True)),
                ('contingency_action', models.CharField(blank=True, max_length=300, null=True)),
                ('progress_on_actions', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
