# Generated by Django 4.1.7 on 2023-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0039_riskregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('incident_photo', models.ImageField(blank=True, null=True, upload_to='post_images')),
            ],
        ),
    ]
