# Generated by Django 4.1.7 on 2023-06-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0040_incidentphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentphotos',
            name='incidentinvestigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hseapp.incidentinvestigation'),
        ),
    ]
