# Generated by Django 4.1.7 on 2023-06-14 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0041_incidentphotos_incidentinvestigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSafetyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('jsa_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_safety_analysis_analysis_by', to='hseapp.staff')),
                ('job_performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_safety_analysis_job_performer', to='hseapp.staff')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_safety_analysis_reviewed_by', to='hseapp.staff')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_safety_analysis_supervisor', to='hseapp.staff')),
            ],
        ),
    ]
