# Generated by Django 4.1.7 on 2023-06-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0042_jobsafetyanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsafetyanalysis',
            name='date_raised',
            field=models.DateField(blank=True, null=True),
        ),
    ]
