# Generated by Django 4.1.7 on 2023-06-15 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0043_jobsafetyanalysis_date_raised'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSafetyEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('job_safety_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hseapp.jobsafetyanalysis')),
            ],
        ),
    ]
