# Generated by Django 4.1.7 on 2023-06-17 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0044_jobsafetyequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSafetySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_steps', models.CharField(blank=True, max_length=300, null=True)),
                ('hazards', models.CharField(blank=True, max_length=300, null=True)),
                ('controls', models.CharField(blank=True, max_length=300, null=True)),
                ('job_safety_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hseapp.jobsafetyanalysis')),
            ],
        ),
    ]
