# Generated by Django 4.1.7 on 2023-06-25 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0047_remove_incident_photo_image_incidenteventphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsafetyanalysis',
            name='job_performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_safety_analysis_job_performer', to='hseapp.staff'),
        ),
    ]
