# Generated by Django 4.1.7 on 2023-06-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0048_alter_jobsafetyanalysis_job_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsafetyanalysis',
            name='analysis_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_safety_analysis_analysis_by', to='hseapp.staff'),
        ),
        migrations.AlterField(
            model_name='jobsafetyanalysis',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_safety_analysis_reviewed_by', to='hseapp.staff'),
        ),
        migrations.AlterField(
            model_name='jobsafetyanalysis',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_safety_analysis_supervisor', to='hseapp.staff'),
        ),
    ]
