# Generated by Django 4.1.7 on 2023-06-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0049_alter_jobsafetyanalysis_analysis_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitToWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(blank=True, max_length=300, null=True)),
                ('location_of_work', models.CharField(blank=True, max_length=300, null=True)),
                ('nature_of_work', models.CharField(blank=True, max_length=300, null=True)),
                ('work_start', models.DateTimeField(blank=True, null=True)),
                ('work_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signitures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_signiture', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('signiture_for', models.CharField(blank=True, max_length=100, null=True)),
                ('position_class', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time_signed', models.DateTimeField(auto_now=True)),
                ('permit_to_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hseapp.permittowork')),
                ('person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hseapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalControls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_mechanisms', models.CharField(blank=True, max_length=300, null=True)),
                ('control_how_will_it_help', models.CharField(blank=True, max_length=300, null=True)),
                ('permit_to_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hseapp.permittowork')),
            ],
        ),
        migrations.CreateModel(
            name='HazardsAndPrecautions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazards', models.CharField(blank=True, max_length=300, null=True)),
                ('precautions', models.CharField(blank=True, max_length=300, null=True)),
                ('permit_to_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hseapp.permittowork')),
            ],
        ),
    ]
