# Generated by Django 4.1.7 on 2023-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0050_permittowork_signitures_physicalcontrols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signitures',
            name='person_signiture',
            field=models.FileField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
