# Generated by Django 4.1.7 on 2023-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0051_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittowork',
            name='work_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permittowork',
            name='work_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
