# Generated by Django 4.1.7 on 2023-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0053_permittowork_work_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSERefrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('hse_document', models.FileField(blank=True, null=True, upload_to='post_documents')),
            ],
        ),
    ]
