# Generated by Django 4.1.7 on 2023-07-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0054_hserefrences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='textbody',
        ),
        migrations.AddField(
            model_name='news',
            name='textbrief',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='textcontent',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
