# Generated by Django 4.1.7 on 2023-07-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0055_remove_news_textbody_news_textbrief_news_textcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('textbrief', models.CharField(blank=True, max_length=500, null=True)),
                ('textcontent', models.TextField(blank=True, max_length=2000, null=True)),
                ('blog_date', models.DateField(auto_now=True)),
                ('person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hseapp.staff')),
            ],
        ),
    ]
