# Generated by Django 4.1.7 on 2023-07-17 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0056_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskregister',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_register_raised_by', to='hseapp.staff'),
        ),
        migrations.AddField(
            model_name='riskregister',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_register_reviewed_by', to='hseapp.staff'),
        ),
    ]
