# Generated by Django 4.1.7 on 2023-07-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0056_alter_signitures_person_signiture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signitures',
            name='person_signiture',
        ),
        migrations.AddField(
            model_name='signitures',
            name='person_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures'),
        ),
    ]
