# Generated by Django 4.1.7 on 2023-07-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0057_riskregister_raised_by_riskregister_reviewed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskregister',
            old_name='owner',
            new_name='responsible_party',
        ),
        migrations.AddField(
            model_name='riskregister',
            name='date_reviewed',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='date_raised',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='RiskRegisterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=300, null=True)),
                ('date_raised', models.DateField(auto_now_add=True, null=True)),
                ('date_reviewed', models.DateField(auto_now=True, null=True)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_register_project_raised_by', to='hseapp.staff')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_register_project_reviewed_by', to='hseapp.staff')),
            ],
        ),
    ]
