# Generated by Django 4.1.7 on 2023-07-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0057_remove_signitures_person_signiture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signitures',
            name='person_signature',
        ),
        migrations.AddField(
            model_name='signitures',
            name='person_signiture',
            field=models.FileField(blank=True, null=True, upload_to='signitures'),
        ),
    ]
