# Generated by Django 4.1.7 on 2023-07-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0058_rename_owner_riskregister_responsible_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskregister',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hseapp.riskregisterproject'),
        ),
    ]
