# Generated by Django 4.1.7 on 2023-07-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0061_safetycard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskregisterproject',
            old_name='project',
            new_name='project_name',
        ),
    ]
