# Generated by Django 4.1.7 on 2023-07-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0062_rename_project_riskregisterproject_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskregister',
            old_name='project',
            new_name='project_name',
        ),
    ]
