# Generated by Django 4.1.7 on 2023-07-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0063_rename_project_riskregister_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetycard',
            name='short_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
