# Generated by Django 6.0.4 on 2026-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0066_safetycardphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeWorkPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='post_documents')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
