# Generated by Django 6.0.4 on 2026-04-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0067_safeworkpractice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('audit_type', models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External'), ('Regulatory', 'Regulatory'), ('Surprise', 'Surprise')], max_length=50, null=True)),
                ('audit_date', models.DateField(blank=True, null=True)),
                ('auditor', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='post_documents')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
