# Generated by Django 6.0.4 on 2026-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0068_hseaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_type', models.CharField(blank=True, choices=[('Fire', 'Fire'), ('Medical', 'Medical'), ('Chemical Spill', 'Chemical Spill'), ('Natural Disaster', 'Natural Disaster'), ('Evacuation', 'Evacuation'), ('Other', 'Other')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('procedures', models.TextField(blank=True, null=True)),
                ('assembly_point', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contacts', models.TextField(blank=True, null=True)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Under Review', 'Under Review'), ('Archived', 'Archived')], default='Draft', max_length=20, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='post_documents')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
