# Generated by Django 6.0.4 on 2026-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0069_emergencyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Chemical', 'Chemical'), ('Biological', 'Biological'), ('Ergonomic', 'Ergonomic'), ('Psychosocial', 'Psychosocial'), ('Environmental', 'Environmental'), ('Other', 'Other')], max_length=50, null=True)),
                ('hazard_description', models.TextField(blank=True, null=True)),
                ('likelihood', models.CharField(blank=True, choices=[('1', 'Rare'), ('2', 'Unlikely'), ('3', 'Possible'), ('4', 'Likely'), ('5', 'Almost Certain')], max_length=2, null=True)),
                ('consequence', models.CharField(blank=True, choices=[('1', 'Insignificant'), ('2', 'Minor'), ('3', 'Moderate'), ('4', 'Major'), ('5', 'Catastrophic')], max_length=2, null=True)),
                ('existing_controls', models.TextField(blank=True, null=True)),
                ('additional_controls', models.TextField(blank=True, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
