# Generated by Django 6.0.4 on 2026-04-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0070_riskmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('report_type', models.CharField(blank=True, choices=[('Incident', 'Incident Report'), ('Audit', 'Audit Report'), ('Training', 'Training Report'), ('Risk', 'Risk Report'), ('Site Visit', 'Site Visit Report'), ('Permit to Work', 'Permit to Work Report'), ('Custom', 'Custom Report')], max_length=50, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='post_documents')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
