# Generated by Django 6.0.4 on 2026-04-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0071_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_title', models.CharField(blank=True, max_length=200, null=True)),
                ('mitigation_action', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Verified', 'Verified')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkplaceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, choices=[('General Safety', 'General Safety'), ('PPE', 'PPE'), ('Fire Safety', 'Fire Safety'), ('Chemical Handling', 'Chemical Handling'), ('Electrical Safety', 'Electrical Safety'), ('Working at Heights', 'Working at Heights'), ('Confined Spaces', 'Confined Spaces'), ('Manual Handling', 'Manual Handling'), ('Other', 'Other')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('consequence', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='post_documents')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
