# Generated by Django 6.0.4 on 2026-04-17 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hseapp', '0073_staff_user_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Lead', 'Lead'), ('Member', 'Member')], default='Member', max_length=20)),
                ('incidentinvestigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='hseapp.incidentinvestigation')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hseapp.staff')),
            ],
        ),
    ]
